create database nailsalons;

create table nailsalon (
	ID int,
	Name varchar(255) unique,
	Address varchar(255) unique
	);


insert into nailsalon (Name, Address) values ('Seven nails', '4721 N Main St K, Houston, TX 77009');
insert into nailsalon (Name, Address) values ('NailBoss Design Salon', '1809 Eldridge Pkwy Suite 112, Houston, TX 77077');
insert into nailsalon (Name, Address) values ('Westbury Nails', '8035 W Airport Blvd #121, Houston, TX 77071');
insert into nailsalon (Name, Address) values ('River Oaks Nails & Spa', '1305 S Shepherd Dr, Houston, TX 77019');
insert into nailsalon (Name, Address) values ('Z Nails Salon', '1828 Airline Dr Suites B, Houston, TX 77009');
insert into nailsalon (Name, Address) values ('Fresh Nails', '9566 Homestead Rd, Houston, TX 77016');
insert into nailsalon (Name, Address) values ('Kelley Nail', '4003 Kelley St, Houston, TX 77026');
insert into nailsalon (Name, Address) values ('Nails Unique', '3733 Westheimer Rd # 2, Houston, TX 77027');
insert into nailsalon (Name, Address) values ('POPULAR NAIL BAR', '9433 Jones Rd, Houston, TX 77065');
insert into nailsalon (Name, Address) values ('Dripped Nails & Spa', '2100 Travis St suite 1505, Houston, TX 77002');
insert into nailsalon (Name, Address) values ('Elegant Nails Spa', '13123 Veterans Memorial Dr, Houston, TX 77014');
insert into nailsalon (Name, Address) values ('Nails And Beauty Bar', '636 Cypress Station Dr, Houston, TX 77090');
insert into nailsalon (Name, Address) values ('LV Nails Spa', '3902 N Shepherd Dr #A1, Houston, TX 77018');
insert into nailsalon (Name, Address) values ('LUVISH NAILS LOUNGE', '5600 Kirby Dr S-1, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Queen Nails', '926 E Tidwell Rd, Houston, TX 77022');
insert into nailsalon (Name, Address) values ('Fizz Nails & Waxing', '6001 Washington Ave ste 300, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('Neon Nail', '1003 W Gray St, Houston, TX 77019');
insert into nailsalon (Name, Address) values ('Citris Nail Spa the Heights', '174 Yale St, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('Nails Spa Co', '2433 Bissonnet St, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Chelsea Nails', '20 E Crosstimbers St, Houston, TX 77022');
insert into nailsalon (Name, Address) values ('Posh Nails and Spa Houston', '5885 San Felipe St #425, Houston, TX 77057');
insert into nailsalon (Name, Address) values ('Trust Thy Nail Tech Studio', '2425 B Emancipation Ave, Houston, TX 77004');
insert into nailsalon (Name, Address) values ('Rice Village Nail and Spa', '2368 Rice Boulevard suite c, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Magic Nails', '4622 Irvington Blvd, Houston, TX 77009');
insert into nailsalon (Name, Address) values ('C Nails & Spa', '5383 Westheimer Rd, Houston, TX 77056');
insert into nailsalon (Name, Address) values ('Fizz Nails', '1533 N Shepherd Dr Ste 150, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('Regal Nails, Salon & Spa', '2727 Dunvale Rd, Houston, TX 77063');
insert into nailsalon (Name, Address) values ('ISLE PEDISPA', '2800 Kirby Dr b234, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('Lee''s Nails', '4802 Almeda Rd, Houston, TX 77004');
insert into nailsalon (Name, Address) values ('Peony Nails & Spa', '12131 Westheimer Rd D, Houston, TX 77077');
insert into nailsalon (Name, Address) values ('ritual pedi spa', 'Located in Ella Plaza, 3464 Ella Blvd, Houston, TX 77018');
insert into nailsalon (Name, Address) values ('Nail Salon', '1523 Little York Rd, Houston, TX 77093');
insert into nailsalon (Name, Address) values ('Tanglewood Nails', '5750 Woodway Dr #132, Houston, TX 77057');
insert into nailsalon (Name, Address) values ('Hollywood Nails & Spa', '1106 Silber Rd Suite A-2, Houston, TX 77055');
insert into nailsalon (Name, Address) values ('Ella Nails Spa', '4222 Ella Blvd, Houston, TX 77018');
insert into nailsalon (Name, Address) values ('Celine Organic Nails & Spa', '5012 Kirby Dr, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('Envimei', '2710 McGowen St, Houston, TX 77004');
insert into nailsalon (Name, Address) values ('American Beauty Nails', '6509 Westheimer Rd Ste C, Houston, TX 77057');
insert into nailsalon (Name, Address) values ('Merchants Park Nail Salon', '918 N Durham Dr Suite A, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('Your Nailtime & Spa', '1950 W Gray St #3, Houston, TX 77019');
insert into nailsalon (Name, Address) values ('Days Spa Nails & Facial', '532 Waugh Dr, Houston, TX 77019');
insert into nailsalon (Name, Address) values ('CH Nails Studio', '4120 Washington Ave Ste C, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('Borgata Nail Salon', '2626 Yale St, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('Coco Nail Spa', '5230 Buffalo Speedway, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Avalon Nail Salon', '1305 S Shepherd Dr a, Houston, TX 77019');
insert into nailsalon (Name, Address) values ('Prestigious Nails', '502 E 20th St A, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('Luxe Nail Bar', '9612 Hwy 6 #120, Missouri City, TX 77459');
insert into nailsalon (Name, Address) values ('U.S Nails Spa', '5909 Scott St F, Houston, TX 77021');
insert into nailsalon (Name, Address) values ('Polished Nail Lounge', '1004 N Shepherd Dr, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('Fancy Nails & Spa', 'Houston, TX 77081');
insert into nailsalon (Name, Address) values ('J C Nails', '8103 Homestead Rd, Houston, TX 77028');
insert into nailsalon (Name, Address) values ('Instyle Nails', '4001 Richmond Ave., Houston, TX 77027');
insert into nailsalon (Name, Address) values ('Parkview Nails', '920 Studemont St, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('House Of Nails', '869 Frostwood Dr, Houston, TX 77024');
insert into nailsalon (Name, Address) values ('Top Art Nails', '4917 Griggs Rd, Houston, TX 77021');
insert into nailsalon (Name, Address) values ('721 Nail Studio', '11693 Westheimer Rd #106, Houston, TX 77077');
insert into nailsalon (Name, Address) values ('Paradise Nail & Facial', '2617 W Holcombe Blvd suite E, Houston, TX 77030');
insert into nailsalon (Name, Address) values ('Paradise Nails & Spa', '7951 Katy Fwy, Houston, TX 77024');
insert into nailsalon (Name, Address) values ('PG NAILS SPA', '11126 Westheimer Rd, Houston, TX 77042');
insert into nailsalon (Name, Address) values ('Glo Nail Lounge', '3004 Yale St #400, Houston, TX 77018');
insert into nailsalon (Name, Address) values ('Summit Nails', '5324 Weslayan St, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Heights Salon', '2428 Yale St B, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('Paloma Beauty', '714 Yale St Suite 2-D, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('E Z Nails', '7210 Capitol St, Houston, TX 77011');
insert into nailsalon (Name, Address) values ('Nails by April', '1509 W 18th St, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('Fizz Nail Lounge', '4717 Westheimer Rd, Houston, TX 77027');
insert into nailsalon (Name, Address) values ('U.S. Nails Houston', '10958 North Fwy, Houston, TX 77037');
insert into nailsalon (Name, Address) values ('Nails of America Riveroaks', '2055 Westheimer Rd suite 135, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('Nail Time', '5535 Memorial Dr M, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('Nice Nail Salon', '7046 Bissonnet St, Houston, TX 77074');
insert into nailsalon (Name, Address) values ('NAILOLOGY', '2902 N Shepherd Dr B, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('Got Nails University', '3749 D, Erie St, Houston, TX 77017');
insert into nailsalon (Name, Address) values ('Maldives Spa & Nails', '2240 Navigation Blvd #600, Houston, TX 77003');
insert into nailsalon (Name, Address) values ('Classic Nails (10% OFF New Customers)', '5201 Richmond Ave. G, Houston, TX 77056');
insert into nailsalon (Name, Address) values ('Heights Nail Spa', '1901 Taylor St F, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('Tu Nail and Spa', '6306 Fairbanks North Houston Rd, Houston, TX 77040');
insert into nailsalon (Name, Address) values ('Nails & Skin Care', '11900 Beechnut St, Houston, TX 77072');
insert into nailsalon (Name, Address) values ('Uptown Galleria Nails & Spa Houston', '2400 Mid Ln SUITE #300, Houston, TX 77027');
insert into nailsalon (Name, Address) values ('Midtown Nails and Spa', '2204 Louisiana St, Houston, TX 77002');
insert into nailsalon (Name, Address) values ('Susan''s Nail & Facial', '2539 Times Blvd, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Vina''s Nails Spa Houston', '3850 S Dairy Ashford Rd, Houston, TX 77082');
insert into nailsalon (Name, Address) values ('Hollywood Hair & Nail Salon', '2409 Grant St B, Houston, TX 77006');
insert into nailsalon (Name, Address) values ('Cosmo Nails & Lashes Studio', '2495 S Braeswood Blvd, Houston, TX 77030');
insert into nailsalon (Name, Address) values ('Palazzio Nail Lounge', '9417 Katy Fwy, Houston, TX 77024');
insert into nailsalon (Name, Address) values ('Nail Studio', '12545 Briar Forest Dr # E, Houston, TX 77077');
insert into nailsalon (Name, Address) values ('Glam Nails & Spa', '608 W Bough Ln, Houston, TX 77024');
insert into nailsalon (Name, Address) values ('VNH Nail Spa', '6606 Irvington Blvd, Houston, TX 77022');
insert into nailsalon (Name, Address) values ('Nails Life Studio', '8571 Westheimer Rd A, Houston, TX 77063');
insert into nailsalon (Name, Address) values ('Miracle Nails', '5741 5727 Westheimer Rd D, Houston, TX 77057');
insert into nailsalon (Name, Address) values ('Accustom Nails & Facials', '5851 Scott St, Houston, TX 77021');
insert into nailsalon (Name, Address) values ('Soho Nail Lounge', '9738 Katy Fwy #200, Houston, TX 77055');
insert into nailsalon (Name, Address) values ('Sola Salon Studios', '535 W 20th St, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('Paris''s Nails and Spa', '7670 Katy Fwy Suite 90, Houston, TX 77024');
insert into nailsalon (Name, Address) values ('Cha Nails Spa (10% Off Coupon)', '4210 San Felipe St, Houston, TX 77027');
insert into nailsalon (Name, Address) values ('Vuvuzela Nail Spa', '18002 Park Row Dr Suite # 200, Houston, TX 77084');
insert into nailsalon (Name, Address) values ('Milano Nail Spa - Galleria', '5000 Westheimer Rd suite 610, Houston, TX 77056');
insert into nailsalon (Name, Address) values ('Sojourn De Nails', '1625 Main St suite a-2, Houston, TX 77002');
insert into nailsalon (Name, Address) values ('The Venetian Nail Spa - MKT', '600 N Shepherd Dr #480, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('Sanctuary Nail Spa', '6363 San Felipe St Suite 200C, Houston, TX 77057');
insert into nailsalon (Name, Address) values ('Gelina Hair & Nail Salon', '1811 Wirt Rd # D, Houston, TX 77055');
insert into nailsalon (Name, Address) values ('West U Nails & Facial', '4001 Bellaire Blvd # E, Houston, TX 77025');
insert into nailsalon (Name, Address) values ('Montrose Nails', '1952 Montrose Blvd C, Houston, TX 77006');
insert into nailsalon (Name, Address) values ('Lux Nail Spa', '9668 Westheimer Rd Suite 100, Houston, TX 77063');
insert into nailsalon (Name, Address) values ('L.A Central Nails', '3821 Old Spanish Trl B, Houston, TX 77021');
insert into nailsalon (Name, Address) values ('Wayside Nails', '900 S Wayside Dr # 750, Houston, TX 77023');
insert into nailsalon (Name, Address) values ('N Nails', '3815 Irvington Blvd D, Houston, TX 77009');
insert into nailsalon (Name, Address) values ('Dreams Nail Spa', '3017 Kirby Dr, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('Instyle Nails', '2370 W Alabama St, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('Star Nails', '1551 Campbell Rd Ste. M, Houston, TX 77055');
insert into nailsalon (Name, Address) values ('N & T Nails', '106 Westheimer Rd C, Houston, TX 77006');
insert into nailsalon (Name, Address) values ('Nail''D It Salon', '226 E Crosstimbers St, Houston, TX 77022');
insert into nailsalon (Name, Address) values ('Trendi Nails & Facial', '5427 Bellaire Blvd a, Bellaire, TX 77401');
insert into nailsalon (Name, Address) values ('Houston Nail & Facials', '14360 Bellaire Blvd # 106, Houston, TX 77083');
insert into nailsalon (Name, Address) values ('Nails by ME', '7679 Clarewood Dr, Houston, TX 77036');
insert into nailsalon (Name, Address) values ('Envision Nails', '3429 Kirby Dr, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('USA #1 Nails', '1409 Wilcrest Dr, Houston, TX 77042');
insert into nailsalon (Name, Address) values ('Nails by Mai Nguyen', '5535 Weslayan St, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('GLO NAILS', '13175 W Lake Houston Pkwy, Houston, TX 77044');
insert into nailsalon (Name, Address) values ('Nails By Mary', '2044 Colquitt St, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('Nailed By Em', '2438 Sunset Blvd, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Retreat Nails Spa', '1507 W 18th St Ste 214, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('West Gray Nails and Spa', '1909 W Gray St, Houston, TX 77019');
insert into nailsalon (Name, Address) values ('Best Nails & Spa', '3727 N MacGregor Way, Houston, TX 77004');
insert into nailsalon (Name, Address) values ('K H Nails', '7431 Cullen Blvd, Houston, TX 77051');
insert into nailsalon (Name, Address) values ('Hi Nails', '12010 Bammel North Houston Rd Unit H, Houston, TX 77066');
insert into nailsalon (Name, Address) values ('GiGi Nail Spa', '3939 Washington Ave B, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('River Oaks Nails & Spa', '2814 Westheimer Rd, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('Le Bijou Nails And Spa', '6134 Westheimer Rd ste c, Houston, TX 77057');
insert into nailsalon (Name, Address) values ('Tulipo Nails and Spa', '13346 Briar Forest Dr #120, Houston, TX 77077');
insert into nailsalon (Name, Address) values ('Nail Design', '6301 Lyons Ave, Houston, TX 77020');
insert into nailsalon (Name, Address) values ('Joy Nail', '6705 Harrisburg Blvd, Houston, TX 77011');
insert into nailsalon (Name, Address) values ('Nails Of America Heights', '2401 N Shepherd Dr Ste A100, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('DKM Nails', '2908 Fountain View Dr, Houston, TX 77057');
insert into nailsalon (Name, Address) values ('Chic Nails And Spa Houston', '5945 Bellaire Blvd, Houston, TX 77081');
insert into nailsalon (Name, Address) values ('Nail Salon & Spa of Bunker Hill', '9710 Katy Fwy #500, Houston, TX 77055');
insert into nailsalon (Name, Address) values ('Dena Nails 1', '3536 Lockwood Dr # K, Houston, TX 77026');
insert into nailsalon (Name, Address) values ('Zewd Nails', '5901 Hillcroft St Shop D5 2nd Floor, Houston, TX 77036');
insert into nailsalon (Name, Address) values ('Milano Nail Spa West U', '5110C Buffalo Speedway, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Pure Lux Nail Spa', '949 N Shepherd Dr, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('Sky Nails Studio', '8949 Westheimer Rd, Houston, TX 77063');
insert into nailsalon (Name, Address) values ('Pro Beauty Nails', '5836 N Main St Suite 1, Houston, TX 77009');
insert into nailsalon (Name, Address) values ('Hair & Nail Salon', '8104 W Tidwell Rd # G, Houston, TX 77040');
insert into nailsalon (Name, Address) values ('River Oak Nails & Spa No 3', '4046 Bellaire Blvd, Houston, TX 77025');
insert into nailsalon (Name, Address) values ('Grand Lux Nail Salon Lounge', '2276 Holcombe Blvd, Houston, TX 77030');
insert into nailsalon (Name, Address) values ('milk + honey', '2800 Kirby Dr Suite A-134, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('The Nail Lounge', '7447 Harwin Dr. Suite #250N, Houston, TX 77036');
insert into nailsalon (Name, Address) values ('M. Vince Nail Spa Regent Square', '3515 W Dallas St #600, Houston, TX 77019');
insert into nailsalon (Name, Address) values ('Mason''s Nails Salon 10% Off Service $30+ Mon-Thurs', '3939 Montrose Blvd, Houston, TX 77006');
insert into nailsalon (Name, Address) values ('Gloss Nail Bar', '504 W Gray St B, Houston, TX 77019');
insert into nailsalon (Name, Address) values ('M. T Nails and Facial Salon LLC', '4912 Washington Ave, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('CK Nails Spa', '5213 Bellaire Blvd, Bellaire, TX 77401');
insert into nailsalon (Name, Address) values ('Secret Escape Nail Lounge', '2272 W Holcombe Blvd, Houston, TX 77030');
insert into nailsalon (Name, Address) values ('Z''Nails', '1416 Featherstone St, Houston, TX 77020');
insert into nailsalon (Name, Address) values ('Alynn’s Nails', '7217 Scott St, Houston, TX 77021');
insert into nailsalon (Name, Address) values ('Sweet Diamond Nail Lounge', '3800 Southwest Fwy #126, Houston, TX 77027');
insert into nailsalon (Name, Address) values ('ISLE PEDISPA', '5819 Kirby Dr, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('The Elysian Boutique', '2723 Yale St #103, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('Nailery', '5819 Gulf Fwy, Houston, TX 77023');
insert into nailsalon (Name, Address) values ('Nail Time', '103 Yale St #500, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('Elegant Nail & Spa', '2620 Shepherd Dr C, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('Elegant Nail', '2726 Bissonnet St # 250, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Peint', '400 Dallas St Ground Floor, Houston, TX 77002');
insert into nailsalon (Name, Address) values ('SWEET MOMENT NAIL AND PEDI SPA', '5821 Kirby Dr, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Nail Therapie HTX', '9121 A Stella Link Rd, Houston, TX 77025');
insert into nailsalon (Name, Address) values ('EXECUTIVE NAILS & SPA WEST UNIVERSITY', '3817 Bellaire Blvd, Houston, TX 77025');
insert into nailsalon (Name, Address) values ('Nails By Judy', '7808 Almeda Rd, Houston, TX 77054');
insert into nailsalon (Name, Address) values ('Splend Nailworks', '9700 Riverstone Ranch Dr suite h, Houston, TX 77089');
insert into nailsalon (Name, Address) values ('Perfect Ten', '5161 San Felipe St # 140, Houston, TX 77056');
insert into nailsalon (Name, Address) values ('Infinite Nails & Spa', '12120 Jones Rd, Houston, TX 77070');
insert into nailsalon (Name, Address) values ('Glossed Glam Factory', '1701 Webster St ste a, Houston, TX 77003');
insert into nailsalon (Name, Address) values ('Dk Nails', '6850 Harrisburg Blvd, Houston, TX 77011');
insert into nailsalon (Name, Address) values ('USA Nails & Spa', '14754 Memorial Dr, Houston, TX 77079');
insert into nailsalon (Name, Address) values ('Paint Nail Bar', '1223 W 34th St c 100, Houston, TX 77018');
insert into nailsalon (Name, Address) values ('Glow Spa & Nails', '2031 Westcreek Ln Ste. 124, Houston, TX 77027');
insert into nailsalon (Name, Address) values ('Uptown Nails & Spa', '3211 Hillcroft St, Houston, TX 77057');
insert into nailsalon (Name, Address) values ('The Venetian Nail Spa Rice Village', '2715 Bissonnet St .Suite 200 ,West University Place, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Lavender & Sage', '3204 Jackson St, Houston, TX 77004');
insert into nailsalon (Name, Address) values ('Nail Trap', '659 Rouse St, Houston, TX 77020');
insert into nailsalon (Name, Address) values ('Synergy Day Spa', '2405 Sunset Blvd, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Polish Parker and Roe', '2313 Edwards St #140, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('Jennifer Nail & Spa', '2515-A, 2515 Rice Boulevard, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Red Hot Nails-Salon, Spa', '250 Patton St, Houston, TX 77009');
insert into nailsalon (Name, Address) values ('Fansi nails', '10950 North Fwy, Houston, TX 77037');
insert into nailsalon (Name, Address) values ('Olivia Rae Nail Boutique', '5781 Woodway Dr, Houston, TX 77057');
insert into nailsalon (Name, Address) values ('Evan Nails', '2751 Gessner Rd #3736, Houston, TX 77080');
insert into nailsalon (Name, Address) values ('Jasmine Nails', '2033 Southwest Fwy #4805, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('High Class Nails By Nam', '9541 S Main St, Houston, TX 77025');
insert into nailsalon (Name, Address) values ('Nails By Tm ($5 OFF Services $45 and up)', '3407 Montrose Blvd A6, Houston, TX 77006');
insert into nailsalon (Name, Address) values ('CH Nails Studio', '4120 Washington Ave Ste C, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('Coco Nail Spa', '5230 Buffalo Speedway, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('U.S. Nails Houston', '10958 North Fwy, Houston, TX 77037');
insert into nailsalon (Name, Address) values ('Uptown Galleria Nails & Spa Houston', '2400 Mid Ln SUITE #300, Houston, TX 77027');
insert into nailsalon (Name, Address) values ('Midtown Nails and Spa', '2204 Louisiana St, Houston, TX 77002');
insert into nailsalon (Name, Address) values ('Post Oak Nail Lounge', '1735 Post Oak Blvd, Houston, TX 77056');
insert into nailsalon (Name, Address) values ('Cha Nails Spa (10% Off Coupon)', '4210 San Felipe St, Houston, TX 77027');
insert into nailsalon (Name, Address) values ('Sojourn De Nails', '1625 Main St suite a-2, Houston, TX 77002');
insert into nailsalon (Name, Address) values ('Sanctuary Nail Spa', '6363 San Felipe St Suite 200C, Houston, TX 77057');
insert into nailsalon (Name, Address) values ('Montrose Nails', '1952 Montrose Blvd C, Houston, TX 77006');
insert into nailsalon (Name, Address) values ('Dreams Nail Spa', '3017 Kirby Dr, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('GiGi Nail Spa', '3939 Washington Ave B, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('Nails Of America Heights', '2401 N Shepherd Dr Ste A100, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('Chic Nails And Spa Houston', '5945 Bellaire Blvd, Houston, TX 77081');
insert into nailsalon (Name, Address) values ('Shine Envision Nails', '3371 Westpark Dr #270, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Mason''s Nails Salon 10% Off Service $30+ Mon-Thurs', '3939 Montrose Blvd, Houston, TX 77006');
insert into nailsalon (Name, Address) values ('Palazzio Nail Lounge', '1544 W Gray St, Houston, TX 77019');
insert into nailsalon (Name, Address) values ('NT Nails Spa', '8330 Long Point Rd Suite B, Houston, TX 77055');
insert into nailsalon (Name, Address) values ('Jasmine Nails', '2033 Southwest Fwy #4805, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('Milano Nail Spa', '2799 Katy Fwy #130, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('Westbury Nails', '8035 W Airport Blvd #121, Houston, TX 77071');
insert into nailsalon (Name, Address) values ('River Oaks Nails & Spa', '1305 S Shepherd Dr, Houston, TX 77019');
insert into nailsalon (Name, Address) values ('Z Nails Salon', '1828 Airline Dr Suites B, Houston, TX 77009');
insert into nailsalon (Name, Address) values ('Sunday Nails Spa', '803 Hwy 6 Ste. E, Houston, TX 77079');
insert into nailsalon (Name, Address) values ('Nails Unique', '3733 Westheimer Rd # 2, Houston, TX 77027');
insert into nailsalon (Name, Address) values ('Julian Nails', '4814 Martin Luther King Blvd, Houston, TX 77021');
insert into nailsalon (Name, Address) values ('Le Q Nails', '614 S Wayside Dr #100, Houston, TX 77011');
insert into nailsalon (Name, Address) values ('LV Nails Spa', '3902 N Shepherd Dr #A1, Houston, TX 77018');
insert into nailsalon (Name, Address) values ('LUVISH NAILS LOUNGE', '5600 Kirby Dr S-1, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Neon Nail', '1003 W Gray St, Houston, TX 77019');
insert into nailsalon (Name, Address) values ('Gyptian Nail Bar', '6400 Southwest Fwy I, Houston, TX 77074');
insert into nailsalon (Name, Address) values ('Jade Nails', '7909 Hillcroft Ave Suite D, Houston, TX 77081');
insert into nailsalon (Name, Address) values ('Citris Nail Spa the Heights', '174 Yale St, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('Nails Spa Co', '2433 Bissonnet St, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Chelsea Nails', '20 E Crosstimbers St, Houston, TX 77022');
insert into nailsalon (Name, Address) values ('Posh Nails and Spa Houston', '5885 San Felipe St #425, Houston, TX 77057');
insert into nailsalon (Name, Address) values ('Fizz Nails', '1533 N Shepherd Dr Ste 150, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('ritual pedi spa', 'Located in Ella Plaza, 3464 Ella Blvd, Houston, TX 77018');
insert into nailsalon (Name, Address) values ('Tanglewood Nails', '5750 Woodway Dr #132, Houston, TX 77057');
insert into nailsalon (Name, Address) values ('Nails Friendly', '13505 Westheimer Rd, Houston, TX 77077');
insert into nailsalon (Name, Address) values ('Plush Nails Studio', '2518 Times Blvd, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Merchants Park Nail Salon', '918 N Durham Dr Suite A, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('TN Nails & Spa', '13711 Westheimer Rd M, Houston, TX 77077');
insert into nailsalon (Name, Address) values ('Your Nailtime & Spa', '1950 W Gray St #3, Houston, TX 77019');
insert into nailsalon (Name, Address) values ('CH Nails Studio', '4120 Washington Ave Ste C, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('Spencer Nails South Houston', '1611 Spencer Hwy Suite H, South Houston, TX 77587');
insert into nailsalon (Name, Address) values ('Rumors Nails & Spa', '7089 Hwy 6 N, Houston, TX 77095');
insert into nailsalon (Name, Address) values ('Venetian Nail Design ($25 Regular Pedicure)', '1510 Eldridge Pkwy S #120, Houston, TX 77077');
insert into nailsalon (Name, Address) values ('Borgata Nail Salon', '2626 Yale St, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('Coco Nail Spa', '5230 Buffalo Speedway, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Avalon Nail Salon', '1305 S Shepherd Dr a, Houston, TX 77019');
insert into nailsalon (Name, Address) values ('Prestigious Nails', '502 E 20th St A, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('La Palm Nails Spa', '5015 Westheimer Rd ste 1425, Houston, TX 77056');
insert into nailsalon (Name, Address) values ('Polished Nail Lounge', '1004 N Shepherd Dr, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('Parkview Nails', '920 Studemont St, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('House Of Nails', '869 Frostwood Dr, Houston, TX 77024');
insert into nailsalon (Name, Address) values ('Glo Nail Lounge', '3004 Yale St #400, Houston, TX 77018');
insert into nailsalon (Name, Address) values ('Summit Nails', '5324 Weslayan St, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('E Z Nails', '7210 Capitol St, Houston, TX 77011');
insert into nailsalon (Name, Address) values ('Fizz Nail Lounge', '4717 Westheimer Rd, Houston, TX 77027');
insert into nailsalon (Name, Address) values ('U.S. Nails Houston', '10958 North Fwy, Houston, TX 77037');
insert into nailsalon (Name, Address) values ('Nice Nail Salon', '7046 Bissonnet St, Houston, TX 77074');
insert into nailsalon (Name, Address) values ('Maldives Spa & Nails', '2240 Navigation Blvd #600, Houston, TX 77003');
insert into nailsalon (Name, Address) values ('OK1 Nails & Hair', '6060 Bellaire Blvd # F, Houston, TX 77081');
insert into nailsalon (Name, Address) values ('Heights Nail Spa', '1901 Taylor St F, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('Uptown Galleria Nails & Spa Houston', '2400 Mid Ln SUITE #300, Houston, TX 77027');
insert into nailsalon (Name, Address) values ('Midtown Nails and Spa', '2204 Louisiana St, Houston, TX 77002');
insert into nailsalon (Name, Address) values ('TEXAN NAILS SPA', '12859 Gulf Fwy, Houston, TX 77034');
insert into nailsalon (Name, Address) values ('Image Nails', '720 Gulfgate Center Mall, Houston, TX 77087');
insert into nailsalon (Name, Address) values ('Vina''s Nails Spa Houston', '3850 S Dairy Ashford Rd, Houston, TX 77082');
insert into nailsalon (Name, Address) values ('Cosmo Nails & Lashes Studio', '2495 S Braeswood Blvd, Houston, TX 77030');
insert into nailsalon (Name, Address) values ('Heavenly Lashes Nail Spa', '2007 W Alabama St c, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('Glam Nails & Spa', '608 W Bough Ln, Houston, TX 77024');
insert into nailsalon (Name, Address) values ('VNH Nail Spa', '6606 Irvington Blvd, Houston, TX 77022');
insert into nailsalon (Name, Address) values ('Miracle Nails', '5741 5727 Westheimer Rd D, Houston, TX 77057');
insert into nailsalon (Name, Address) values ('Post Oak Nail Lounge', '1735 Post Oak Blvd, Houston, TX 77056');
insert into nailsalon (Name, Address) values ('Cha Nails Spa (10% Off Coupon)', '4210 San Felipe St, Houston, TX 77027');
insert into nailsalon (Name, Address) values ('Sojourn De Nails', '1625 Main St suite a-2, Houston, TX 77002');
insert into nailsalon (Name, Address) values ('Sanctuary Nail Spa', '6363 San Felipe St Suite 200C, Houston, TX 77057');
insert into nailsalon (Name, Address) values ('West U Nails & Facial', '4001 Bellaire Blvd # E, Houston, TX 77025');
insert into nailsalon (Name, Address) values ('Montrose Nails', '1952 Montrose Blvd C, Houston, TX 77006');
insert into nailsalon (Name, Address) values ('Dreams Nail Spa', '3017 Kirby Dr, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('Instyle Nails', '2370 W Alabama St, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('Star Nails', '1551 Campbell Rd Ste. M, Houston, TX 77055');
insert into nailsalon (Name, Address) values ('N & T Nails', '106 Westheimer Rd C, Houston, TX 77006');
insert into nailsalon (Name, Address) values ('Nail''D It Salon', '226 E Crosstimbers St, Houston, TX 77022');
insert into nailsalon (Name, Address) values ('Aura Nail & Spa', '3201 N Shepherd Dr #115, Houston, TX 77018');
insert into nailsalon (Name, Address) values ('Eden Nails & Spa (10% & 15% OFF Happy Hour: 9:30AM - 3PM)', '8236 Kirby Dr, Houston, TX 77054');
insert into nailsalon (Name, Address) values ('GLO NAILS', '13175 W Lake Houston Pkwy, Houston, TX 77044');
insert into nailsalon (Name, Address) values ('Retreat Nails Spa', '1507 W 18th St Ste 214, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('GiGi Nail Spa', '3939 Washington Ave B, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('Nails Of America Heights', '2401 N Shepherd Dr Ste A100, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('Houston Nails', '6515 Tidwell Rd, Houston, TX 77016');
insert into nailsalon (Name, Address) values ('Chic Nails And Spa Houston', '5945 Bellaire Blvd, Houston, TX 77081');
insert into nailsalon (Name, Address) values ('Milano Nail Spa West U', '5110C Buffalo Speedway, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Shine Envision Nails', '3371 Westpark Dr #270, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Pure Lux Nail Spa', '949 N Shepherd Dr, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('Pro Beauty Nails', '5836 N Main St Suite 1, Houston, TX 77009');
insert into nailsalon (Name, Address) values ('River Oak Nails & Spa No 3', '4046 Bellaire Blvd, Houston, TX 77025');
insert into nailsalon (Name, Address) values ('Grand Lux Nail Salon Lounge', '2276 Holcombe Blvd, Houston, TX 77030');
insert into nailsalon (Name, Address) values ('Houston''s Nails', '11826 Westheimer Rd, Houston, TX 77077');
insert into nailsalon (Name, Address) values ('Mason''s Nails Salon 10% Off Service $30+ Mon-Thurs', '3939 Montrose Blvd, Houston, TX 77006');
insert into nailsalon (Name, Address) values ('Gloss Nail Bar', '504 W Gray St B, Houston, TX 77019');
insert into nailsalon (Name, Address) values ('M. T Nails and Facial Salon LLC', '4912 Washington Ave, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('CK Nails Spa', '5213 Bellaire Blvd, Bellaire, TX 77401');
insert into nailsalon (Name, Address) values ('Griggs Nails', '5074 Griggs Rd, Houston, TX 77021');
insert into nailsalon (Name, Address) values ('Nails By Ann', '6364 Martin Luther King Blvd b1, Houston, TX 77021');
insert into nailsalon (Name, Address) values ('Palazzio Nail Lounge', '1544 W Gray St, Houston, TX 77019');
insert into nailsalon (Name, Address) values ('Z''Nails', '1416 Featherstone St, Houston, TX 77020');
insert into nailsalon (Name, Address) values ('Blue Sky Nails', '9990D Kleckley Dr, Houston, TX 77075');
insert into nailsalon (Name, Address) values ('The Elysian Boutique', '2723 Yale St #103, Houston, TX 77008');
insert into nailsalon (Name, Address) values ('Nail Time', '103 Yale St #500, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('Elegant Nail & Spa', '2620 Shepherd Dr C, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('Fancy Nails & Spa', '13531 Bammel North Houston Rd, Houston, TX 77066');
insert into nailsalon (Name, Address) values ('NT Nails Spa', '8330 Long Point Rd Suite B, Houston, TX 77055');
insert into nailsalon (Name, Address) values ('EXECUTIVE NAILS & SPA WEST UNIVERSITY', '3817 Bellaire Blvd, Houston, TX 77025');
insert into nailsalon (Name, Address) values ('Palace Nails Spa', '8498 S Sam Houston Pkwy E #1500, Houston, TX 77075');
insert into nailsalon (Name, Address) values ('Edgebrook Nails', '9820 Gulf Fwy, Houston, TX 77034');
insert into nailsalon (Name, Address) values ('D Nails & Spa', '10142 Hammerly Blvd, Houston, TX 77080');
insert into nailsalon (Name, Address) values ('Glow Spa & Nails', '2031 Westcreek Ln Ste. 124, Houston, TX 77027');
insert into nailsalon (Name, Address) values ('Uptown Nails & Spa', '3211 Hillcroft St, Houston, TX 77057');
insert into nailsalon (Name, Address) values ('The Venetian Nail Spa Rice Village', '2715 Bissonnet St .Suite 200 ,West University Place, Houston, TX 77005');
insert into nailsalon (Name, Address) values ('Lavender & Sage', '3204 Jackson St, Houston, TX 77004');
insert into nailsalon (Name, Address) values ('Polish Parker and Roe', '2313 Edwards St #140, Houston, TX 77007');
insert into nailsalon (Name, Address) values ('Evan Nails', '2751 Gessner Rd #3736, Houston, TX 77080');
insert into nailsalon (Name, Address) values ('Jasmine Nails', '2033 Southwest Fwy #4805, Houston, TX 77098');
insert into nailsalon (Name, Address) values ('Nails By Tm ($5 OFF Services $45 and up)', '3407 Montrose Blvd A6, Houston, TX 77006');
insert into nailsalon (Name, Address) values ('Milano Nail Spa', '2799 Katy Fwy #130, Houston, TX 77007');

delete from nailsalon where Name='Tran''s Nails';
delete from nailsalon where Name='KT Nails';
delete from nailsalon where Name='Caesar''s Nails and Spa';
delete from nailsalon where Name='Vina''s Nails Spa Houston';
delete from nailsalon where Name='Nails By Ann';
delete from nailsalon where Name='Peony Nails & Spa';
delete from nailsalon where Name='Westheimer Nails & Spa';
delete from nailsalon where Name='King Nails Royal Oaks';
delete from nailsalon where Name='Beaute Skin Nail';
delete from nailsalon where Name='Cathy''s Nail';
delete from nailsalon where Name='Trishy''s Spatique';
delete from nailsalon where Name='MC Nails';
delete from nailsalon where Name='Lux Nail Spa';
delete from nailsalon where Name='Dairy Nails';
delete from nailsalon where Name='Perfect Nails & Spa';
delete from nailsalon where Name='Natural Nails & Skin Care';
delete from nailsalon where Name='Paris Nails';
delete from nailsalon where Name='Studio Nails & Spa';
delete from nailsalon where Name='KBK Nails';
delete from nailsalon where Name='Houston''s Nails';
delete from nailsalon where Name='CASHBACK NAIL BAR';
delete from nailsalon where Name='Chung''s Nail Creations';
delete from nailsalon where Name='Diva Nails';
delete from nailsalon where Name='Amy''s Classic Nails';
delete from nailsalon where Name='Da-Vi Nails';
delete from nailsalon where Name='721 Nail Studio';
delete from nailsalon where Name='nailsxbellaa';
delete from nailsalon where Name='Classic Nail and Spa';
delete from nailsalon where Name='Julie Unique Hair & Nails';
delete from nailsalon where Name='L V Nails';
delete from nailsalon where Name='Sun Ray Nails & Spa';
delete from nailsalon where Name='Nails By Honey';
delete from nailsalon where Name='GRANDLUX NAIL LOUNGE WESTHEIMER & DUNVALE';
delete from nailsalon where Name='Season of Nail';
delete from nailsalon where Name='Nails by ME';
delete from nailsalon where Name='Venetian Nail Design ($25 Regular Pedicure or Regular Shellac Manicure)';
delete from nailsalon where Name='Lovely Nails and Spa';
delete from nailsalon where Name='Zewd Nails';
delete from nailsalon where Name='Wynn Nails Spa';
delete from nailsalon where Name='Maxim Nails & Spa';
delete from nailsalon where Name='Be-Be Nails Spa';
delete from nailsalon where Name='USA Nails & Spa';
delete from nailsalon where Name='Pink Nail Lounge & Boutique';
delete from nailsalon where Name='Nails Life Studio';
delete from nailsalon where Name='Le Bijou Nails And Spa';
delete from nailsalon where Name='Oasis Nails Lounge';
delete from nailsalon where Name='Sanctuary Nail Spa';
delete from nailsalon where Name='Gyptian Nail Bar';
delete from nailsalon where Name='Pretty Nails Spa';
delete from nailsalon where Name='Orchid Salon Day Spa';
delete from nailsalon where Name='OPI on Nails';
delete from nailsalon where Name='FM Nail Spa';
delete from nailsalon where Name='Lily''s Nails';
delete from nailsalon where Name='Cutest Clawz';
delete from nailsalon where Name='Fine Nails';
delete from nailsalon where Name='NailBoss Design Salon';
delete from nailsalon where Name='Silky Nails';
delete from nailsalon where Name='AKYISH Japanese Retreat & Spa';
delete from nailsalon where Name='Logo Nails';
delete from nailsalon where Name='Nail Studio';